name: ci

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "* 10 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "linlcccc@gmail.com"
          git config --local user.name "Linlccc"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "daily task"
          git push
